enable_png = true

[[thw]]
template = "Volunteer"
zug = "Alle"
names = ",KF,SAN,peer,psFK,AB,Ko,OJB,SM,StvOB,Vw"
special = ""
dir = "personen"

[[thw]]
template = "Volunteer"
zug = "OV"
names = "AB,BÖH"
special = ""
dir = "personen"

[[thw]]
template = "Fachberater"
zug = "OV"
names = "FaBe,TeBe,THW,BFB,Flugleiter"
special = ""
dir = "personen"

[[thw]]
template = "Fuehrung"
zug = "OV"
names = ",OB"
special = ""
dir = "personen"

#### FK ####

[[thw]]
template = "Volunteer"
zug = "Alle"
names = "IuK,RiFu"
special = ""
dir = "personen"

[[thw]]
template = "Fuehrung"
zug = "FK"
names = "FmFü,LdF"
special = ""
dir = "personen"

[[thw]]
template = "Gruppenfuehrer"
zug = "FK"
names = "F,K"
special = ""
dir = "personen"

[[thw]]
template = "Truppfuehrer"
zug = "FK"
names = "F,K"
special = ""
dir = "personen"

[[thw]]
template = "Truppe"
zug = "FK"
names = "FM,IuK,WV"
special = ""
dir = "einheit"

[[thw]]
template = "Fuehrungstruppe"
zug = "FK"
names = "FüKom,FüGeh"
special = ""
dir = "einheit"

[[thw]]
template = "Gruppe"
zug = "FK"
names = "K"
special = ""
dir = "einheit"

[[thw]]
template = "Fuehrungsgruppe"
zug = "FK"
names = "F"
special = ""
dir = "einheit"

[[thw]]
template = "Zugfuehrer"
zug = "FK"
names = "FZ-FK,FK"
special = ""
dir = "personen"

[[thw]]
template = "Zugtruppfuehrer"
zug = "FK"
names = "FZ-FK,FK"
special = ""
dir = "personen"

[[thw]]
template = "Stabsgruppe"
zug = "FK"
names = "Stab"
special = ""
dir = "einheit"

[[thw]]
template = "Stab"
zug = "FK"
names = "SGL,S1,S2,S3,S4,S5,S6"
special = ""
dir = "personen"

[[thw]]
template = "Fuehrungszug"
zug = "FK"
names = "FK"
special = ""
dir = "einheit"

[[thw]]
template = "Zugtrupp"
zug = "FK"
names = "FK"
special = ""
dir = "einheit"

[[thw]]
template = "Weitverkehrstrupp"
zug = "FK"
names = "WV"
special = ""
dir = "einheit"

[[thw]]
template = "Anhaenger"
zug = "FK"
names = "FüLa,K 1t,RiFu"
special = ""
dir = "fahrzeuge"

[[thw]]
template = "Fahrzeug"
zug = "FK"
names = "FmKW,FüKomKW,FüKW"
special = ""
dir = "fahrzeuge"


##### TZ #####


[[thw]]
template = "Gruppenfuehrer"
zug = "TZ"
names = "I,N,BT,E,Öl,Sp,L,ÖGA,B,SB,BrB,TW,W,ENT,GA,JuGr,SEEBA,SEEWA,SEELift"
special = ""
dir = "personen"

[[thw]]
template = "Truppfuehrer"
zug = "TZ"
names = "I,N,BT,E,Öl,Sp,L,ÖGA,B,SB,BrB,TW,W,ENT,GA,JuGr,SEEBA,SEEWA,SEELift,ESS,MHP,UL"
special = ""
dir = "personen"

[[thw]]
template = "Truppe"
zug = "TZ"
names = ",I,N,BT,E,Öl,Sp,L,ÖGA,B,SB,BrB,TW,W,ENT,GA,JuGr,SEEBA,SEEWA,SEELift,ESS,MHP,UL"
special = ""
dir = "einheit"

[[thw]]
template = "Gruppe"
zug = "TZ"
names = ",I,N,BT,E,Öl,Sp,L,ÖGA"
special = ""
dir = "einheit"

[[thw]]
template = "Gruppe"
zug = "TZ"
names = "B"
special = ",ASH,EGS"
dir = "einheit"

[[thw]]
template = "Gruppe"
zug = "TZ"
names = "SB,BrB,TW,W"
special = ",A,B"
dir = "einheit"

[[thw]]
template = "Gruppe"
zug = "TZ"
names = ",Öl,O,WP"
special = ",A,B,C"
dir = "einheit"


[[thw]]
template = "Gruppe"
zug = "TZ"
names = "R"
special = ",A(R),A,A(B),B,C"
dir = "einheit"

[[thw]]
template = "GruppeOhneFuehrung"
zug = "TZ"
names = ",AEGr,ENT,GA,JuGr,SEEBA,SEEWA,SEELift"
special = ""
dir = "einheit"

[[thw]]
template = "Zugfuehrer"
zug = "TZ"
names = "TZ"
special = ""
dir = "personen"

[[thw]]
template = "Zugtruppfuehrer"
zug = "TZ"
names = "TZ"
special = ""
dir = "personen"

[[thw]]
template = "Zug"
zug = "TZ"
names = "TZ"
special = ""
dir = "einheit"

[[thw]]
template = "Zugtrupp"
zug = "TZ"
names = "TZ"
special = ""
dir = "einheit"


[[thw]]
template = "Staffel"
zug = "TZ"
names = ""
special = ""
dir = "einheit"


[[thw]]
template = "Verband"
zug = "TZ"
names = ",Feldlager,"
special = ""
dir = "einheit"


[[thw]]
template = "Anhaenger"
zug = "TZ"
names = "NEA"
special = ",50 kVA LiMa,200 kVA,600 kVA"
dir = "fahrzeuge"


[[thw]]
template = "Anhaenger"
zug = "TZ"
names = "SwPu"
special = ",5000 l pro min,15000 l pro min,25000 l pro min"
dir = "fahrzeuge"

[[thw]]
template = "Anhaenger"
zug = "TZ"
names = "O 2t"
special = ",A,B"
dir = "fahrzeuge"

[[thw]]
template = "Abrollbehaelter"
zug = "TZ"
names = ",Wks"
special = ""
dir = "fahrzeuge"

[[thw]]
template = "Gelaendefahrzeug"
zug = "TZ"
names = ",BRmG,"
special = ""
dir = "fahrzeuge"

[[thw]]
template = "Boot"
zug = "TZ"
names = ",kl Boot,MzAB,MzB,MzPt,RuSB,SchlB"
special = ""
dir = "fahrzeuge"

[[thw]]
template = "Fahrzeug"
zug = "TZ"
names = ",ERS, GKW 7t, GKW I, GKW II,LKW-Lkr,MTW FGr,MTW,PKW,THV"
special = ""
dir = "fahrzeuge"


[[thw]]
template = "Fahrzeug"
zug = "TZ"
names = "Stapler"
special = ",2t,3t"
dir = "fahrzeuge"


[[thw]]
template = "Fahrzeug"
zug = "TZ"
names = "Telelader"
special = ",2t"
dir = "fahrzeuge"


[[thw]]
template = "Fahrzeug"
zug = "TZ"
names = "LKW-K"
special = ",9t,LKr 1.5t,LKr"
dir = "fahrzeuge"

[[thw]]
template = "Fahrzeug"
zug = "TZ"
names = "LKW-Lbw"
special = ",7t"
dir = "fahrzeuge"

[[thw]]
template = "Gelaendefahrzeug"
zug = "TZ"
names = ",Stapler,Kipper,,MLW II,MLW III,MLW IV,MLW V,MzGW,MzKW,PKW,PKW WV,Bagger,Radlader"
special = ""
dir = "fahrzeuge"

[[thw]]
template = "Kettenfahrzeug"
zug = "TZ"
names = ",Bagger"
special = ""
dir = "fahrzeuge"

[[thw]]
template = "Sattelzug"
zug = "TZ"
names = ",SZM,WLF"
special = ""
dir = "fahrzeuge"

##### LOG #####

[[thw]]
template = "Zugfuehrer"
zug = "Log"
names = "Log,FZ-Log"
special = ""
dir = "personen"

[[thw]]
template = "Zugtruppfuehrer"
zug = "Log"
names = "Log,FZ-Log"
special = ""
dir = "personen"

[[thw]]
template = "Zug"
zug = "Log"
names = "Log"
special = ""
dir = "einheit"

[[thw]]
template = "LogTruppe"
zug = "Log"
names = "Log-M,Log-VG,Log-V,TS"
special = ""
dir = "einheit"

[[thw]]
template = "LogGruppe"
zug = "Log"
names = "Log-MW,Log-V,Log"
special = ""
dir = "einheit"

[[thw]]
template = "Truppe"
zug = "Log"
names = "Log"
special = ""
dir = "einheit"

[[thw]]
template = "Zugtrupp"
zug = "Log"
names = "Log"
special = ""
dir = "einheit"

##### Sonstig #####

[[thw]]
template = "LogVerband"
zug = "Log"
names = ",Logistik"
special = ""
dir = "einheit"

[[thw]]
template = "Zug"
zug = "VOST"
names = "VOST"
special = ""
dir = "einheit"


[[thw]]
template = "Gebaeude"
zug = "Alle"
names = ",OV,RST,LV,Ltg,AZ,Log"
special = ""
dir = "gebaeude"

[[thw]]
template = "Gebaeude"
zug = "Alle"
names = "LV"
special = "HeRpSl,Bayern,Küste,BaWü,BEBBST,HBNI,HHMVSH,SNTH"
dir = "gebaeude"

[[thw]]
template = "Anhaenger"
zug = "Alle"
names = ",0.5t,2t,6t,7t, BT 2t,DLE,FKH,I 2T,kl Boot,Kühl,LiMa,Log-MW 2t,MzAB,MzB,MzPt,PF 12t,RettH,Ru 12t,SchlB,Sp 2t,Spül,SEA,Tiefl 18t,TWAA,Wks"
special = ""
dir = "fahrzeuge"



[[fw]]
template = "Gruppenfuehrer"
zug = ""
names = ""
special = ""
dir = "personen"

[[fw]]
template = "Fuehrung"
zug = ""
names = ",A,S,W"
special = ""
dir = "personen"

[[fw]]
template = "Volunteer"
zug = ""
names = ",A,Ma,Me,S,W"
special = ""
dir = "personen"

[[fw]]
template = "Gebaeude"
zug = ""
names = "Fw"
special = ""
dir = "gebaeude"

[[bw]]
template = "Gruppenfuehrer"
zug = ""
names = ""
special = ""
dir = "personen"

[[bw]]
template = "Fuehrung"
zug = ""
names = ""
special = ""
dir = "personen"

[[bw]]
template = "Truppfuehrer"
zug = ""
names = ""
special = ""
dir = "personen"

[[bw]]
template = "Zugfuehrer"
zug = ""
names = ""
special = ""
dir = "personen"

[[bw]]
template = "Staffelfuehrer"
zug = ""
names = ""
special = ""
dir = "personen"

[[bw]]
template = "Gruppenfuehrer"
zug = ""
names = ""
special = ""
dir = "personen"

[[bw]]
template = "GruppeOhneFuehrung"
zug = ""
names = ",BW"
special = ""
dir = "einheit"

[[bw]]
template = "Kettenfahrzeug"
zug = ""
names = ""
special = ""
dir = "fahrzeuge"

[[bw]]
template = "Fahrzeug"
zug = ""
names = ""
special = ""
dir = "fahrzeuge"

[[bw]]
template = "Gelaendefahrzeug"
zug = ""
names = ""
special = ""
dir = "fahrzeuge"

[[alle]]
template = "Fuehrungsgruppe"
zug = ""
names = ""
special = ""
dir = "einheit"

[[alle]]
template = "Fuehrungstruppe"
zug = ""
names = ""
special = ""
dir = "einheit"

[[alle]]
template = "Fuehrungsstaffel"
zug = ""
names = ""
special = ""
dir = "einheit"

[[alle]]
template = "Gruppe"
zug = ""
names = ""
special = ""
dir = "einheit"

[[alle]]
template = "Truppe"
zug = ""
names = ""
special = ""
dir = "einheit"

[[alle]]
template = "Zug"
zug = ""
names = ""
special = ""
dir = "einheit"

[[alle]]
template = "Staffel"
zug = ""
names = ""
special = ""
dir = "einheit"

[[alle]]
template = "Abrollbehaelter"
zug = ""
names = ""
special = ""
dir = "fahrzeuge"

[[alle]]
template = "Boot"
zug = ""
names = ""
special = ""
dir = "fahrzeuge"

[[alle]]
template = "Schienenfahrzeug"
zug = ""
names = ""
special = ""
dir = "fahrzeuge"

[[alle]]
template = "Kraftrad"
zug = ""
names = ""
special = ""
dir = "fahrzeuge"

[[alle]]
template = "Gelaendefahrzeug"
zug = ""
names = ""
special = ""
dir = "fahrzeuge"

[[alle]]
template = "Fahrzeug"
zug = ""
names = ""
special = ""
dir = "fahrzeuge"


[[alle]]
template = "Kettenfahrzeug"
zug = ""
names = ""
special = ""
dir = "fahrzeuge"


[[alle]]
template = "Hubschrauber"
zug = ""
names = ""
special = ""
dir = "fahrzeuge"


[[alle]]
template = "Flugzeug"
zug = ""
names = ""
special = ""
dir = "fahrzeuge"

[[alle]]
template = "Fahrzeug"
zug = ""
names = ""
special = ""
dir = "fahrzeuge"

[[alle]]
template = "Fahrrad"
zug = ""
names = ""
special = ""
dir = "fahrzeuge"

[[alle]]
template = "Anhaenger"
zug = ""
names = ""
special = ""
dir = "fahrzeuge"

[[pol]]
template = "Gruppenfuehrer"
zug = ""
names = ""
special = ""
dir = "personen"

[[zoll]]
template = "Gruppenfuehrer"
zug = ""
names = ""
special = ""
dir = "personen"

[[rettung]]
template = "Gruppenfuehrer"
zug = ""
names = ""
special = ""
dir = "personen"

[[kats]]
template = "Gruppenfuehrer"
zug = ""
names = ""
special = ""
dir = "personen"




[[thw]]
template = "Stelle"
zug = "Alle"
names = ",EAL,EL,BR500,Flgr,TEL,AFüSt,FüStab,KatSL,UEAL,ÖEL"
special = ""
dir = "Führungsstelle"