enable_png = false

[[thw]]
template = "Helfer"
zug = ""
names = ",KF,SAN"
special = ""

[[thw]]
template = "Fachberater"
zug = ""
names = "FaBe,TeBe"
special = ""

[[thw]]
template = "Gruppenfuehrer"
zug = "FK"
names = "F,K"
special = ""

[[thw]]
template = "Truppfuehrer"
zug = "FK"
names = "F,K"
special = ""

[[thw]]
template = "Truppe"
zug = "FK"
names = "FM,IuK,WV"
special = ""

[[thw]]
template = "Fuehrungstruppe"
zug = "FK"
names = "FüKom,FüGeh"
special = ""

[[thw]]
template = "Gruppe"
zug = "FK"
names = "K"
special = ""

[[thw]]
template = "Fuehrungsgruppe"
zug = "FK"
names = "F"
special = ""

[[thw]]
template = "Zugfuehrer"
zug = "FK"
names = "FZ-FK,FK"
special = ""

[[thw]]
template = "Zugtruppfuehrer"
zug = "FK"
names = "FZ-FK,FK"
special = ""

[[thw]]
template = "Stabsgruppe"
zug = "FK"
names = "Stab"
special = ""

[[thw]]
template = "Stab"
zug = "FK"
names = "SGL,S1,S2,S3,S4,S5,S6"
special = ""

[[thw]]
template = "Fuehrungszug"
zug = "FK"
names = "FK"
special = ""

[[thw]]
template = "Zugtrupp"
zug = "FK"
names = "FK"
special = ""

[[thw]]
template = "Weitverkehrstrupp"
zug = "FK"
names = "WV"
special = ""


##### TZ #####


[[thw]]
template = "Gruppenfuehrer"
zug = "TZ"
names = "I,N,BT,E,Öl,Sp,L,ÖGA,B,SB,BrB,TW,W,ENT,GA,JuGr,SEEBA,SEEWA,SEELift"
special = ""

[[thw]]
template = "Truppfuehrer"
zug = "TZ"
names = "ESS"
special = ""

[[thw]]
template = "Truppe"
zug = "TZ"
names = ",I,N,BT,E,Öl,Sp,L,ÖGA,B,SB,BrB,TW,W,ENT,GA,JuGr,SEEBA,SEEWA,SEELift,ESS,MHP,UL"
special = ""

[[thw]]
template = "Gruppe"
zug = "TZ"
names = ",I,N,BT,E,Öl,Sp,L,ÖGA"
special = ""

[[thw]]
template = "Gruppe"
zug = "TZ"
names = "B"
special = ",ASH,EGS"

[[thw]]
template = "Gruppe"
zug = "TZ"
names = "SB,BrB,TW,W"
special = ",A,B"

[[thw]]
template = "Gruppe"
zug = "TZ"
names = ",Öl,O,WP"
special = ",A,B,C"


[[thw]]
template = "Gruppe"
zug = "TZ"
names = "R"
special = ",A(R),A,A(B),B,C"

[[thw]]
template = "GruppeOhneFuehrung"
zug = "TZ"
names = ",AEGr,ENT,GA,JuGr,SEEBA,SEEWA,SEELift"
special = ""

[[thw]]
template = "Zugfuehrer"
zug = "TZ"
names = "TZ"
special = ""

[[thw]]
template = "Zugtruppfuehrer"
zug = "TZ"
names = "TZ"
special = ""

[[thw]]
template = "Zug"
zug = "TZ"
names = "TZ"
special = ""

[[thw]]
template = "Zugtrupp"
zug = "TZ"
names = "TZ"
special = ""


[[thw]]
template = "Staffel"
zug = "TZ"
names = ""
special = ""


[[thw]]
template = "Verband"
zug = "TZ"
names = ",Feldlager,"
special = ""


##### LOG #####
[[thw]]
template = "Zugfuehrer"
zug = "Log"
names = "Log,FZ-Log"
special = ""

[[thw]]
template = "Zugtruppfuehrer"
zug = "Log"
names = "Log,FZ-Log"
special = ""

[[thw]]
template = "Zug"
zug = "Log"
names = "Log"
special = ""

[[thw]]
template = "LogTruppe"
zug = "Log"
names = "Log-M,Log-VG,Log-V,TS"
special = ""

[[thw]]
template = "LogGruppe"
zug = "Log"
names = "Log-MW,Log-V,Log"
special = ""

[[thw]]
template = "Truppe"
zug = "Log"
names = "Log"
special = ""

[[thw]]
template = "Zugtrupp"
zug = "Log"
names = "Log"
special = ""

##### Sonstig #####

[[thw]]
template = "LogVerband"
zug = "Log"
names = ",Logistik"
special = ""

[[thw]]
template = "Zug"
zug = "VOST"
names = "VOST"
special = ""